/*
SQLyog Community v13.1.9 (64 bit)
MySQL - 8.0.30 : Database - alumni
*********************************************************************
*/

/*!40101 SET NAMES utf8 */;

/*!40101 SET SQL_MODE=''*/;

/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
CREATE DATABASE /*!32312 IF NOT EXISTS*/`alumni` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;

USE `alumni`;

/*Table structure for table `alumnidata` */

DROP TABLE IF EXISTS `alumnidata`;

CREATE TABLE `alumnidata` (
  `id` int NOT NULL AUTO_INCREMENT,
  `aname` varchar(45) NOT NULL,
  `yeargrad` varchar(45) NOT NULL,
  `address` varchar(100) NOT NULL,
  `birthdate` varchar(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `alumnidata` */

insert  into `alumnidata`(`id`,`aname`,`yeargrad`,`address`,`birthdate`) values 
(8,'john nigels s.sipe','2019','gumamela','2023-09-20'),
(9,'Its me','2023','asd','2023-09-18'),
(10,'try lan','damn','finsa','2023-09-26'),
(11,'Its me','xada','just','2023-09-28');

/*Table structure for table `approvaljob` */

DROP TABLE IF EXISTS `approvaljob`;

CREATE TABLE `approvaljob` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(45) DEFAULT NULL,
  `description` varchar(45) DEFAULT NULL,
  `ptime` varchar(45) DEFAULT NULL,
  `pdate` varchar(45) DEFAULT NULL,
  `requirement` varchar(100) DEFAULT NULL,
  `link` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=13 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `approvaljob` */

insert  into `approvaljob`(`id`,`title`,`description`,`ptime`,`pdate`,`requirement`,`link`) values 
(3,'another example','asd','10:03 AM','9/26/2023','','rewr'),
(9,'MY trial','asd lang sa','05:34 PM','9/27/2023','kailangan kabalo mo type','https://www.youtube.com/'),
(10,'Alumni','Alumni','07:32 PM','9/27/2023','just Alumni','https://www.youtube.com/watch?v=egEpsrPY6rQ');

/*Table structure for table `books` */

DROP TABLE IF EXISTS `books`;

CREATE TABLE `books` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(45) NOT NULL,
  `desc` varchar(45) NOT NULL,
  `cover` varchar(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=12 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `books` */

insert  into `books`(`id`,`title`,`desc`,`cover`) values 
(2,'title1','desc 1','cover2.png'),
(3,'title1','desc 1','cover2.png'),
(4,'title1','desc 1','cover2.png'),
(5,'title1','desc 1','cover2.png'),
(11,'sadas','asd','xz');

/*Table structure for table `eventdata` */

DROP TABLE IF EXISTS `eventdata`;

CREATE TABLE `eventdata` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(45) NOT NULL,
  `stime` varchar(45) NOT NULL,
  `sdate` varchar(45) NOT NULL,
  `ptime` varchar(45) DEFAULT NULL,
  `pdate` varchar(45) DEFAULT NULL,
  `description` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=17 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `eventdata` */

insert  into `eventdata`(`id`,`title`,`stime`,`sdate`,`ptime`,`pdate`,`description`) values 
(9,'sdfsd','1:19 PM','09/28/2023','01:19 PM','9/17/2023',NULL),
(10,'Buwan ng Wika','3:22 PM','10/05/2023','01:22 PM','9/17/2023',NULL),
(11,'Alumni HomeComing','2:22 PM','09/18/2023','02:20 PM','9/18/2023',NULL),
(12,'example 342','5:47 AM','09/26/2023','05:45 AM','9/26/2023',NULL),
(13,'My New Event','10:07 AM','09/28/2023','08:07 AM','9/28/2023',NULL),
(14,'Another cya','8:47 PM','09/28/2023','08:47 AM','9/28/2023',NULL),
(15,'BSCS SEMINAR','3:36 PM','2023-09-29','03:34 PM','9/29/2023',NULL),
(16,'cs days','8:00 AM','2023-10-29','06:44 PM','10/1/2023',NULL);

/*Table structure for table `joboppdata` */

DROP TABLE IF EXISTS `joboppdata`;

CREATE TABLE `joboppdata` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(45) DEFAULT NULL,
  `description` varchar(45) DEFAULT NULL,
  `ptime` varchar(45) DEFAULT NULL,
  `pdate` varchar(45) DEFAULT NULL,
  `requirement` varchar(100) DEFAULT NULL,
  `link` varchar(100) DEFAULT NULL,
  `image` blob,
  `approved` int DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=36 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `joboppdata` */

insert  into `joboppdata`(`id`,`title`,`description`,`ptime`,`pdate`,`requirement`,`link`,`image`,`approved`) values 
(1,'work 1','its just my work','09:50 AM','12/12/2023','elementary Graduate','www.facebook.com',NULL,NULL),
(3,'Job2','sadas','06:39 PM','7/6/2023','sadas','dasd',NULL,NULL),
(4,'Job4','i will catch you ','09:43 PM','9/6/2023','no brain','http://www.youtube.com',NULL,NULL),
(8,'job22 ','job lang sya','07:40 AM','9/8/2023','nothing','https://www.youtube.com/watch?v=u72H_zZzkcw',NULL,NULL),
(9,'virtual assistant','full-time','02:23 PM','9/18/2023','tor','',NULL,NULL),
(25,'another example','asd','10:03 AM','9/26/2023','','rewr',NULL,NULL),
(26,'MY trial','asd lang sa','05:34 PM','9/27/2023','kailangan kabalo mo type','https://www.youtube.com/',NULL,NULL),
(30,'asd','asdas','08:45 AM','9/26/2023','qweq','sdwrf',NULL,NULL),
(33,'youtube','youtube','07:40 PM','9/27/2023','just watch','https://www.youtube.com/watch?v=tTpTQ4kBLxA&list=RDtTpTQ4kBLxA&start_radio=1&rv=tTpTQ4kBLxA&t=2',NULL,NULL),
(34,'VLOGGER','TRAVEL VLOG','03:46 PM','9/28/2023','','https://www.messenger.com/t/5425401150897048',NULL,NULL),
(35,'IT SUPPORT','MUST BE  A DEGREE HOLDER','03:29 PM','9/29/2023','2X2 ID\nRESUME\nAPPLICATION LETTER','https://www.youtube.com/watch?v=vq-nvJ6q8bI',NULL,NULL);

/*Table structure for table `login` */

DROP TABLE IF EXISTS `login`;

CREATE TABLE `login` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(45) NOT NULL,
  `email` varchar(100) NOT NULL,
  `password` varchar(45) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=16 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `login` */

insert  into `login`(`id`,`name`,`email`,`password`) values 
(1,'John Nigels Sapilan Sipe','nigesipe@gmail.com','PMAsoon17*()'),
(2,'James Ivan Remedios','jamesivanremedios@gmail.com','PMAsoon17*()'),
(3,'Jamaica M. Dayanan ','jamaicadayanan@gmail.com','PMAsoon17*()'),
(4,'John','nigesipe@gmail.com','123'),
(5,'Matthew Maxwell Sipe','matt@gmail.com','PMAsoon17*()'),
(6,'Matt Sipe','matt24@gmail.com','PMAsoon17*()'),
(7,'hey','hey@gmail.com','PMAsoon17*()'),
(8,'hhh','nigesipe@gmail.com','143212PMAsoon'),
(9,'Matthew Maxwell Magdadaro','matthew@gmail.com','143212PMAsoon'),
(10,'SHANE','shane@gmail.com','Shane143212'),
(11,'name','namepassword@gmail.com','NAMEpassword123'),
(12,'jamaica','jamaica@gmail.com','JAMaica123'),
(13,'Alumni','alumni@gmail.com','Alumni143212'),
(14,'James Ivan Remedios','jamesivan143@gmail.com','JAMESivan123'),
(15,'JOHN NIGELS SAPILAN','nigesipe@gmail.com','PMAsoon143');

/*Table structure for table `newsdata` */

DROP TABLE IF EXISTS `newsdata`;

CREATE TABLE `newsdata` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(45) NOT NULL,
  `ptime` varchar(45) NOT NULL,
  `pdate` varchar(45) NOT NULL,
  `description` varchar(200) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=11 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `newsdata` */

insert  into `newsdata`(`id`,`title`,`ptime`,`pdate`,`description`) values 
(1,'Example','07:50 AM','2023-12-23','It just example'),
(2,'News 2','08:34 PM','2023-03-12','Second news to new'),
(3,'123','05:17 PM','9/5/2023','qwe df'),
(4,'asd','06:58 PM','9/5/2023','sada'),
(5,'my News','08:10 PM','9/7/2023','Its Just my News'),
(10,'CS DAYS','03:31 PM','9/29/2023','CS META 2023');

/*Table structure for table `registration` */

DROP TABLE IF EXISTS `registration`;

CREATE TABLE `registration` (
  `id` int NOT NULL AUTO_INCREMENT,
  `lname` varchar(45) DEFAULT NULL,
  `fname` varchar(45) DEFAULT NULL,
  `mname` varchar(45) DEFAULT NULL,
  `phoneno` varchar(45) DEFAULT NULL,
  `gender` varchar(45) DEFAULT NULL,
  `address` varchar(100) DEFAULT NULL,
  `bday` varchar(45) DEFAULT NULL,
  `yeargrad` varchar(45) DEFAULT NULL,
  `email` varchar(100) DEFAULT NULL,
  `password` varchar(45) DEFAULT NULL,
  `employment_status` varchar(100) DEFAULT NULL,
  `current_job` varchar(100) DEFAULT NULL,
  `year_current_job` int DEFAULT NULL,
  `job_duration_after_grad` varchar(100) DEFAULT NULL,
  `position_current_job` varchar(100) DEFAULT NULL,
  `place_current_job` varchar(100) DEFAULT NULL,
  `previous_job` varchar(100) DEFAULT NULL,
  `year_previous_job` int DEFAULT NULL,
  `position_previous_job` varchar(100) DEFAULT NULL,
  `place_previous_job` varchar(100) DEFAULT NULL,
  `engage_studies` varchar(100) DEFAULT NULL,
  `enroll_studies` varchar(100) DEFAULT NULL,
  `eligibility` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=348 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `registration` */

insert  into `registration`(`id`,`lname`,`fname`,`mname`,`phoneno`,`gender`,`address`,`bday`,`yeargrad`,`email`,`password`,`employment_status`,`current_job`,`year_current_job`,`job_duration_after_grad`,`position_current_job`,`place_current_job`,`previous_job`,`year_previous_job`,`position_previous_job`,`place_previous_job`,`engage_studies`,`enroll_studies`,`eligibility`) values 
(1,'ALDO','ALMER','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(2,'ALMOJALLAS','ROMELYN','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(3,'ARCOY','REZELLE MAE ','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(4,'AMPUNAN','CRISTY JANE','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(5,'ARCOY','SHEILA MAE','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(6,'ARMECIN ','MARILOU','C.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(7,'BALASE','JAY','V.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(8,'BAÑEZ','MARICEL','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(9,'BETACHE','DEZERIE','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(10,'BITAMOR','JOHN PAUL','W.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(11,'BUENDIA','ELLAINE GRACE','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(12,'CALDEO','WYNNIE VEILLE','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(136,'CANENCIA','ALMA','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(137,'CABANLIT','CARLO','Y.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(138,'DIMEN','ANGELIC','G.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(139,'ESPARAGO','JUNREY','C.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(140,'HELAMON','RECHEL','C.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(141,' HILA-OS','PEARLY','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(142,'LLANDA','NICKIELYN','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(143,'MALIGRO ','MELANIE','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(144,'MAPA','IMEE-LENE','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(145,'OTANDOY','JESSA','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(146,'PABUAYA','JAMAICA','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(147,'SABADO','MERY CRIS','V.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(148,'SABANAL','CRIS SAN','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(149,'SARSABA','ROSE','L.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(150,'SANGEDAS','CRISELLE MAY','C.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(151,'SENADJAN','JUVIE','J.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(152,'PENIG','MAYBEL','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(153,'SONGCUYA','MARK DOMINICK','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(154,'TALASAN','ABEGUEL','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(155,'YUSOPH','MUHAMMAD KHAN','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(156,'ACOSTA','JELEVIE','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(157,' BAGUIA','JENNIFER','J.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(158,'BALINDONG','RAILA','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(159,'BASMAYOR','BRUZELLE','R.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(160,'CONSEGO','MERY JANE','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(161,'DE ASIS','NIÑAFLOR','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(162,'DIWA','WAIDEN','N.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(163,'GALLEGOS','ARLENE','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(164,'GERODIAS','LIBERTH','V.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(165,'GUMBAN JR.','LEONARDO','E.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(166,'JARALVE','NICO','C.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(167,'JUTBA','ANALYN','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(168,'LONGAY','JOAN','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(169,'LUCIRO','EVA','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(170,'MAHINAY','ANELYN','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(171,'MENDEZ JR.','MELVYN','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(172,'MOJADO','HERMINO','G.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(173,'MOJELLO','CHERRY JANE','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(174,'ORCULLO','MA. FLORIZA ','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(175,'PAHAGANAS','ROSEMIE','R.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(176,'PARAMI','ANGELIE','O.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(177,'PASIGNASIGNA ','CRISTINA','O.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(178,'PASIGNASIGNA ','CRISTYLOU','O.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(179,'TAMBOBOY','GERLYN','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(180,'TOMA','OMRA','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(181,' ABENES','KENT RALPH','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(184,'ARCHIBAL','ONEIL','R.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(185,'BALAWING','REYNALYN','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(186,'BANABANA','RYAN','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(187,'BANGHAL','JEDIEL','G.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(188,'CALING','NEGLYN','C.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(189,'CALISO','RYAN','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(190,'CUIZON ','JENELYN','R.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(191,'DAUB','KEVIN JONE','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(192,'DELA CERNA','MELVIR','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(193,'GAMPONGAN','MICHELLE','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(194,'MALALIS','RONNIE','O.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(195,'MORALES','KATRINA GRACE','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(196,'RONDA','AGNES','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(197,'SAYSON','HANIE MIE','C.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(198,'VELOS','RICHEL','J.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(199,'ABARQUEZ ','JOVELYN','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(200,'AMARILLE','RANEFEL','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(201,'ARSENAL','SUNNY BOY','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(202,'ASO','MICHEAL','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(203,'BABAO','ARGIE LOU','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(204,'BALIQUIG','ALVIN','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(205,'BALUCAN','DAINARD','K.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(206,'BANGLOS','CYRIL JOHN','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(207,'BANGUIH','MARK ANTHONY','G.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(208,'BASTIONG','IVY','E.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(209,'BAYO','JESSA','L.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(210,'CAANGAY','ARJAN','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(211,'CABALLERO JR.','HIPOLITO','F.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(212,'DELA CRUZ','RUBY GALE','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(213,'DIAZ','GEVELYN','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(214,'DIONSON','WELCEL GEM','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(215,'JAICTIN','ELISA','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(216,'LUNIZA','BABES','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(217,' MEDICO','MART','L.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(218,' MENDIG','MARVIN','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(219,'MONTON','RAMEL','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(220,'MOSQUEDA','REMELYN','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(221,'PADAO','NECKIE','C.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(222,'SIAPEL','FLORDELIZ','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(223,'VILLEGAS','RANDY','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(224,'YOUNG','EARL WYN','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(225,'ABDUL RAHMAN','ISMAEL','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(226,'ABERIN','ALEXIE','E.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(227,'ALEJANDRINO','CRISLENE','G.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(228,'ALVIOLA','JOYLYN','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(229,'APAO','JUDE MICHAEL','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(230,' BACLA-AN JR.','SEVERO','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(231,'BUDAY','NORAINA','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(232,'CAINGLES','JOANA CRIS','G.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(233,'CASO','RICHARD','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(234,'CELADA','MAY ANN','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(235,'CUARESMA','VEHVERLY','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(236,'DA-AN','PAUL NICK','E.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(237,'DAMIANO','JIHAN','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(238,'DELFIN','JERALD','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(239,'DENDEN','JESSA','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(240,'DUNCO','CATHERINE','O.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(241,'EDULAN','DAISY','C.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(242,'ELID','BEN-A-MYRO','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(243,' FERNANDEZ','MARIBEL','O.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(244,'FLORES','REYMEL','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(245,'GOMERA','ARREN BRENDON','Z.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(246,'HINOGIN','JONARD','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(247,'JACOSALEM','MELIZA','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(248,'JUMAMEL','RHONEL','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(249,'LASTIMADO','IVANY','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(250,'LUCERO','ALMIRA','E.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(251,'MAGLASANG','LOVELY PRINCESS',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(252,'MAÑO','JUDITH','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(253,'MARAVILLAS','JOCELYN','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(254,'MOLINA','MARY MIE','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(255,'MONER','ASNIDA','C.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(256,'OPERIO','ROSE MARIE','R.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(257,' PADAYAO','VENA MAE','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(258,'PAYOD','APRIL JANE','Q.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(259,'PEREZ','JERALDINE','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(260,'PONCE','AN-AN','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(261,'RENDULA','JOANIE','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(262,'ROMA','ELTON','E.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(263,'RUIZ','MARIA THERESA','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(264,'RUIZAL','LOVELIE CLAIRE','G.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(265,'SABADO','DJ MAE','J.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(266,'SANGU-AN','LOEUMAY','H.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(267,'SANICO','PEJIE','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(268,'SENO','MARGIE','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(269,'SIDIC','AILYN','L.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(270,'SUBA','NORBERTA','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(271,'TAMPARONG ','JEAN','J.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(272,'TOLOMIA','DANIEL','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(273,'TORNITO','JESSA ROSE','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(274,'VILLAHERMOSA','RUBY ANN','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(275,'YAMSON','JERAMIE','N.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(276,'YAP','JAMES CARLO','V.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(277,'ABAD','WILMAR','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(278,'ABARQUEZ','MARIEL ','O.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(279,'ALBERIO','MARY BON ','R.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(280,'ALBITO','RONEL ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(281,'ALCALA','ALFER','Y.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(282,'ALEJANDRINO','CRISLENE','G.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(283,'AMPIG','MARK JOAQUIN','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(284,'AGAWIN','HANNY','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(285,'AROJO','JASON','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(286,'BAGUIO','NICK JAY','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(287,'BANAWA','RODETH','G.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(288,'BAYHONAN','ANGEL','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(289,'BISAYAS','CHARILYN','J.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(290,'BRAGAT','ALEXANDER','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(291,'CABANSAG','DIANA','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(292,'CAUGAN','GIAMERAH ','E.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(293,'CLAPANO','ELMARK JOHN','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(294,'COLOT','MARK JOHN','R.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(295,'DE ASIS','NIÑA FLOR','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(296,'DECLARO','GERLIE ANN','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(297,'DELOS SANTOS','CRISA','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(298,'DURAN','JUDY ANN','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(299,'EBIN','RENA','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(300,'ESMAEL','HESHAM','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(301,'FRONDA','MARY GRACE','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(302,'GATAB','DAISY MAE','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(303,'GEMPARO','SHELLA MIE','F.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(304,'GILLAMAC JR.','RONALD','D.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(305,'GINES','JESSA MAE','E.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(306,'HIPOS','DECILY','G.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(307,'ILIGAN','NORILYN','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(308,'JUMACHAG','KAREN','N.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(309,'JUTBA','ANNALY','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(310,'KAYA JR.','JAYDAN REY',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(311,'LACIA','JEMAR','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(312,'LAFABLE','JUNEREL','S. ',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(313,'MAGONGAYA','ABDULAZIZ','L.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(314,'MASLA','NAMSARIE','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(315,'MEDICO','JOMER','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(316,'MIRA','ARGIE','O.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(317,'NERO','MARIE JAICAR','P.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(318,'NOCUM','BABY VANESSA NICOLE','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(319,'OCAY','MELCHOR','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(320,'ONTEVEROS','CRISTIGIE','V.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(321,'PAPIC','MARIVIE','L.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(322,'PAQUIT','STEVEN','W.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(323,'PATAGAN JR.','LINOEL','O.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(324,'PONCE','AN-AN','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(325,'PUHOT','ANNIE JANE','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(326,'RAMOS','RENALYN','J.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(327,'ROBLES','RENANTE','S.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(328,'ROMA','ELTON','E.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(329,'SALIPOT','RACHEL LEE','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(330,'FERNANDEZ','KARL FERNANDO','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(331,'TAALA','JAMES ANTHONY','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(332,'TABUCO','JAYSON','V.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(333,'TAGHAP','NYREL ANN','M.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(334,'ARINGO','JUNREY','L.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(335,'BANSALAO','MC ARWIN','L.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(336,'BUGHAW','JELANIE','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(337,'DENOY','REY MARK','F.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(338,'FUENTES','JOANNIE','L.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(339,'GUALIZA JR.','RICARDO','C.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(340,'LINGATING','JUDY ANN','G.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(341,'MANUEL','MARK BRIAN','A.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(342,'MANLUPIG','AMIE','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(343,'MASILLONES','TERESA','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(344,'PEÑA','LANIE','T.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(345,'PICPIC','ANALIZA','B.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(346,'RAMOGA','MARCELYN','L.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL),
(347,'TUNGAL','VAMBHE','L.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

/*Table structure for table `stories` */

DROP TABLE IF EXISTS `stories`;

CREATE TABLE `stories` (
  `id` int NOT NULL AUTO_INCREMENT,
  `title` varchar(255) NOT NULL,
  `img` blob NOT NULL,
  `desc` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=70 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

/*Data for the table `stories` */

insert  into `stories`(`id`,`title`,`img`,`desc`) values 
(1,'test','nice',NULL),
(2,'test','nice',NULL),
(3,'test','nice',NULL),
(4,'test','nice',NULL),
(5,'test','nice',NULL),
(6,'ss','image-1697609018408.jpg','ssss'),
(7,'TEST 3','image-1697609478466.jpg','GWAPOKO'),
(8,'JOHN NIGELS SIPE','image-1697609548335.jpg','niceeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeeee'),
(9,'','image-1697609599680.jpg','jjjjjjjjjjj'),
(10,'james','image-1697609614553.jpg','jjj'),
(11,'JAMES','image-1697609795008.jpg','SSSSSS'),
(12,'nigel','image-1697610136701.jpg','gwapoo'),
(13,'SIPE, JOHN NIGELS S.','image-1697610681295.jpg','Lorem ipsum dolor sit amet, consectetur adipiscing elit. Fusce in tincidunt tortor. Suspendisse facilisis lacinia neque, ac posuere augue malesuada nec. Nunc dictum efficitur nulla, et ullamcorper justo. Nulla facilisi. Curabitur lacinia id odio non fermentum. Aenean laoreet ac urna at laoreet. Phasellus vel turpis quam. Suspendisse varius dui eget semper viverra. Proin id sapien vitae odio convallis luctus. Aliquam erat volutpat. Sed semper in risus at ullamcorper. Sed in tincidunt mi. Integer bibendum, tortor at suscipit varius, massa dui consectetur dolor, nec venenatis purus libero quis libero.'),
(14,'john','image-1697611680724.jpg','jjj'),
(15,'NIGEL, JOHN SIPE','image-1697612090328.jpg','Graduation is a significant milestone in a person\'s life, marking the culmination of years of hard work, dedication, and personal growth. It symbolizes the completion of an educational journey, whether it\'s high school, college, or any other form of formal education. Graduation ceremonies are typically filled with a mix of emotions, including a sense of accomplishment, excitement for the future, and a touch of nostalgia for the experiences and friendships forged along the way. One of the most cherished aspects of graduation is the sense of achievement it brings. It\'s a moment where all the late nights, exams, papers, and sacrifices suddenly make sense, as you stand on the threshold of a new beginning. Whether it\'s donning a cap and gown or receiving a diploma, the act of graduation is a powerful symbol of one\'s capacity for growth, learning, and resilience. It\'s a testament to the effort and determination that have gone into reaching this point. Graduation also represents a bridge to the future. As graduates walk across the stage, they are not just leaving their academic institution but also stepping into a world of possibilities. The ceremony is a launching pad for careers, adventures, and new experiences. It\'s a time when the future is wide open, and the world is full of opportunities waiting to be seized. Graduates often feel a mix of excitement, uncertainty, and hope as they contemplate the path ahead, making it a truly transformative moment in their lives.'),
(16,'jamaica, dayanan','image-1697612173301.jpg','Graduation is a significant milestone in a person\'s life, marking the culmination of years of hard work, dedication, and personal growth. It symbolizes the completion of an educational journey, whether it\'s high school, college, or any other form of formal education. Graduation ceremonies are typically filled with a mix of emotions, including a sense of accomplishment, excitement for the future, and a touch of nostalgia for the experiences and friendships forged along the way. One of the most cherished aspects of graduation is the sense of achievement it brings. It\'s a moment where all the late nights, exams, papers, and sacrifices suddenly make sense, as you stand on the threshold of a new beginning. Whether it\'s donning a cap and gown or receiving a diploma, the act of graduation is a powerful symbol of one\'s capacity for growth, learning, and resilience. It\'s a testament to the effort and determination that have gone into reaching this point. Graduation also represents a bridge to the future. As graduates walk across the stage, they are not just leaving their academic institution but also stepping into a world of possibilities. The ceremony is a launching pad for careers, adventures, and new experiences. It\'s a time when the future is wide open, and the world is full of opportunities waiting to be seized. Graduates often feel a mix of excitement, uncertainty, and hope as they contemplate the path ahead, making it a truly transformative moment in their lives.'),
(17,'d','image-1697612753404.jpg','sss'),
(18,'sssss','image-1697612827543.jpg','<img src={`${imageBaseUrl}/${img}`} alt=\"\" className=\"portfolio__img\" />'),
(19,'REMDIOS, JAMES IVAN A.','image-1697613103427.jpg','gwapoooooooooooooooooooooooooooooooooooooooooooooooooooooo #army'),
(20,'DAYANAN, JAMAICA','image-1697613165601.jpg','IWWWWWWWWWWWWWWWWW'),
(21,'nigel','image-1697613384783.jpg','NICE'),
(22,'ALUMNI','image-1697614040803.jpg','SSSSSSSSSSSSSS'),
(23,'james dayanan','image-1697614197436.html','love birds'),
(24,'REMEDIOS, DAYANAN','image-1697614265058.png','iww lovebirds'),
(25,'s','image-1697614400318.jpg','s'),
(26,'sss','image-1697616658860.jpg','sssss'),
(27,'jeps','image-1697810315344.jpg','DDDDDDDDDDDDDD'),
(28,'DAYANAN, JAMAICA','image-1697810393546.jpg','app.put(\"/api/studentData/:id\", (req, res) => {\r\n  const id = req.params.id;\r\n  const { firstName, lastName, sectionID } = req.body;\r\n\r\n  const sqlUpdate =\r\n    \"UPDATE student_list SET firstName = ?, lastName = ?, sectionID = ? WHERE id = ?\";\r\n\r\n  console.log(\"SQL Query:\", sqlUpdate);\r\n  console.log(\"Parameters:\", [firstName, lastName, sectionID, id]);\r\n\r\n  db.query(sqlUpdate, [firstName, lastName, sectionID, id], (err, result) => {\r\n    if (err) {\r\n      console.log(err);\r\n      res'),
(29,'test','image-1697810422745.jpg',''),
(30,'NEXT','image-1697812021601.jpg','WWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWWW'),
(31,'test1','image-1697812159799.jpg','ssssssssssssss'),
(32,'TEST','/uploads/image-1697813047489.jpg','SS'),
(33,'test1','/uploads/image-1697813148053.jpg','sss'),
(34,'test5','/uploads/image-1697813505002.jpg','sss'),
(35,'hhhhh','/uploads/image-1697814412301.jpg','jj'),
(36,'bn','/uploads/image-1697814438674.jpg','jj'),
(37,'test6','/uploads/image-1697815207262.jpg','ssssssssssssssss'),
(38,'test again','/uploads/image-1697816102518.jpg','test'),
(39,'s','image-1697816291401.jpg','s'),
(40,'ssss','image-1697816887980.jpg','sss'),
(41,'ss','image-1697817598793.jpg','s'),
(42,'ss','image-1697817987348.jpg','ss'),
(43,'s','image-1697818276504-151288594.jpg','ss'),
(44,'TEST50','image-1697819266901.jpg','DSDS'),
(45,'SS','image-1697823045197.jpg','SSSSSS'),
(46,'s','image-1697823335506.jpg','s'),
(47,'JAMES IVAN REMEDIOS','image-1697823357509.jpg','LOREM'),
(48,'sssss','image-1697824101689.jpg','ss'),
(49,'ss','image-1697824480459.jpg','sss'),
(50,'ss','image-1697824510025.jpg','ss'),
(51,'james','image-1697824642444.jpg','ss'),
(52,'JAMES','image-1697824824585.jpg','SS'),
(53,'TEST','image-1697824854095.jpg','SSSSSSS'),
(54,'nige','image-1697825529402.jpg','sssssss'),
(55,'Sipe, John Nigels S.','image-1697827186459.jpg','GWAPO'),
(56,'dayanan, jamaica A','image-1697829038439.jpg','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa'),
(57,'JAMES IVAN','image-1697829062421.jpg','AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA'),
(58,'JOHN NIGELS SAPILAN SIPE','image-1697833171873.jpg','SS'),
(59,'JOHN','image-1697834327421.jpg','SS'),
(60,'JJ','image-1697834384664.jpg','KKKKKKK'),
(61,'title','img','desc'),
(62,'title','img','desc'),
(63,'title','img','desc'),
(64,'title','img','desc'),
(65,'title','img','desc'),
(66,'seroy','image-1697836716202.jpg','seroy'),
(67,'HEY','image-1698226268692.jpg','JJ'),
(68,'TEST','image-1698227400252.jpg','ss'),
(69,'hello','image-1698229642789.jpg','ss');

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;
